---
- name: Install Python and Apache webserver on CentOS/RHEL systems
  hosts: localhost
  become: yes
  tasks:
    - name: Install Python
      yum:
        name: python
        state: present

    - name: Install Apache webserver
      yum:
        name: httpd
        state: present

    - name: Start and enable Apache webserver
      service:
        name: httpd
        state: started
        enabled: yes
